// <auto-generated />
using System;
using MediRecords.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MediRecords.Domain.Migrations
{
    [DbContext(typeof(MediRecordsDbContext))]
    [Migration("20260327110816_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MediRecords.Domain.Entities.Allergy", b =>
                {
                    b.Property<int>("AllergyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AllergyId"));

                    b.Property<string>("Allergen")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("NotedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("Reaction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Severity")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("AllergyId");

                    b.HasIndex("PatientId");

                    b.ToTable("Allergy", (string)null);
                });

            modelBuilder.Entity("MediRecords.Domain.Entities.Appointment", b =>
                {
                    b.Property<int>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AppointmentId"));

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<int>("ProviderId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("AppointmentId");

                    b.HasIndex("PatientId");

                    b.HasIndex("ProviderId");

                    b.ToTable("Appointment");
                });

            modelBuilder.Entity("MediRecords.Domain.Entities.AuditLog", b =>
                {
                    b.Property<int>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuditId"));

                    b.Property<string>("Action")
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("Resource")
                        .HasColumnType("VARCHAR(255)");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("AuditId");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLog");
                });

            modelBuilder.Entity("MediRecords.Domain.Entities.CarePlan", b =>
                {
                    b.Property<int>("CarePlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CarePlanId"));

                    b.Property<string>("GoalsJSON")
                        .IsRequired()
                        .HasColumnType("VARCHAR(MAX)");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasColumnType("VARCHAR(MAX)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("CarePlanId");

                    b.HasIndex("PatientId");

                    b.ToTable("CarePlan", (string)null);
                });

            modelBuilder.Entity("MediRecords.Domain.Entities.ClinicalTemplate", b =>
                {
                    b.Property<int>("TemplateId")
                        .HasColumnType("int");

                    b.Property<string>("ContentJSON")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("TemplateType")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("TemplateId");

                    b.HasIndex("CreatedBy");

                    b.ToTable("ClinicalTemplate");
                });

            modelBuilder.Entity("MediRecords.Domain.Entities.Document", b =>
                {
                    b.Property<int>("DocumentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DocumentID"));

                    b.Property<string>("DocType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("EncounterID")
                        .HasColumnType("int");

                    b.Property<string>("FileURI")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("PatientID")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<int>("UploadedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadedDate")
                        .HasColumnType("datetime");

                    b.HasKey("DocumentID");

                    b.HasIndex("EncounterID");

                    b.HasIndex("PatientID");

                    b.ToTable("Document");
                });

            modelBuilder.Entity("MediRecords.Domain.Entities.Encounter", b =>
                {
                    b.Property<int>("EncounterId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<int>("ProviderId")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("VisitType")
                        .IsRequired()
                        .HasColumnType("nvarchar(MAX)");

                    b.HasKey("EncounterId");

                    b.HasIndex("PatientId");

                    b.HasIndex("ProviderId");

                    b.ToTable("Encounter");
                });

            modelBuilder.Entity("MediRecords.Domain.Entities.FollowUp", b =>
                {
                    b.Property<int>("FollowupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FollowupId"));

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("EncounterId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("VARCHAR(MAX)");

                    b.Property<DateTime>("RecommendedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("FollowupId");

                    b.HasIndex("EncounterId");

                    b.ToTable("FollowUp");
                });

            modelBuilder.Entity("MediRecords.Domain.Entities.ImagingOrder", b =>
                {
                    b.Property<int>("ImagingOrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImagingOrderId"));

                    b.Property<int>("EncounterId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("VARCHAR(MAX)");

                    b.Property<DateTime>("OrderedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("StudyType")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.HasKey("ImagingOrderId");

                    b.HasIndex("EncounterId");

                    b.ToTable("ImagingOrder");
                });

            modelBuilder.Entity("MediRecords.Domain.Entities.ImagingReport", b =>
                {
                    b.Property<int>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReportId"));

                    b.Property<string>("Findings")
                        .IsRequired()
                        .HasColumnType("VARCHAR(MAX)");

                    b.Property<int>("ImagingOrderId")
                        .HasColumnType("int");

                    b.Property<string>("Impression")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.Property<DateTime>("ReportDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("ReportId");

                    b.HasIndex("ImagingOrderId");

                    b.ToTable("ImagingReport");
                });

            modelBuilder.Entity("MediRecords.Domain.Entities.Immunization", b =>
                {
                    b.Property<int>("ImmunizationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImmunizationId"));

                    b.Property<string>("Dose")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("GivenDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("Vaccine")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("ImmunizationId");

                    b.HasIndex("PatientId");

                    b.ToTable("Immunization", (string)null);
                });

            modelBuilder.Entity("MediRecords.Domain.Entities.LabOrder", b =>
                {
                    b.Property<int>("LabOrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LabOrderId"));

                    b.Property<int>("EncounterId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderedBy")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("TestJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LabOrderId");

                    b.HasIndex("EncounterId");

                    b.HasIndex("OrderedBy");

                    b.ToTable("LabOrder");
                });

            modelBuilder.Entity("MediRecords.Domain.Entities.LabResult", b =>
                {
                    b.Property<int>("ResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResultId"));

                    b.Property<int>("LabOrderId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ResultDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ResultJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("ResultId");

                    b.HasIndex("LabOrderId");

                    b.ToTable("LabResult");
                });

            modelBuilder.Entity("MediRecords.Domain.Entities.MedicalHistory", b =>
                {
                    b.Property<int>("HistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HistoryId"));

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RecordedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("HistoryId");

                    b.HasIndex("PatientId");

                    b.ToTable("MedicalHistory", (string)null);
                });

            modelBuilder.Entity("MediRecords.Domain.Entities.MedicationList", b =>
                {
                    b.Property<int>("MedId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MedId"));

                    b.Property<string>("Dose")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("DrugName")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("Route")
                        .HasColumnType("VARCHAR(50)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("MedId");

                    b.HasIndex("PatientId");

                    b.ToTable("MedicationList", (string)null);
                });

            modelBuilder.Entity("MediRecords.Domain.Entities.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("VARCHAR(MAX)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("NotificationId");

                    b.HasIndex("UserId");

                    b.ToTable("Notification");
                });

            modelBuilder.Entity("MediRecords.Domain.Entities.Patient", b =>
                {
                    b.Property<int>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PatientId"));

                    b.Property<string>("AddressJSON")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactInfo")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<string>("Gender")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MRN")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("PrimaryProviderId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("PatientId");

                    b.HasIndex("MRN")
                        .IsUnique();

                    b.HasIndex("PrimaryProviderId");

                    b.ToTable("Patient");
                });

            modelBuilder.Entity("MediRecords.Domain.Entities.Prescription", b =>
                {
                    b.Property<int>("PrescriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PrescriptionId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EncounterId")
                        .HasColumnType("int");

                    b.Property<int>("ProviderId")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("PrescriptionId");

                    b.HasIndex("EncounterId");

                    b.ToTable("Prescription");
                });

            modelBuilder.Entity("MediRecords.Domain.Entities.PrescriptionItem", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemId"));

                    b.Property<string>("Dose")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("DrugName")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.Property<int>("DurationDays")
                        .HasColumnType("int");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PrescriptionId")
                        .HasColumnType("int");

                    b.HasKey("ItemId");

                    b.HasIndex("PrescriptionId");

                    b.ToTable("PrescriptionItem");
                });

            modelBuilder.Entity("MediRecords.Domain.Entities.ProblemList", b =>
                {
                    b.Property<int>("ProblemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProblemId"));

                    b.Property<string>("Diagnosis")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ProblemId");

                    b.HasIndex("PatientId");

                    b.ToTable("ProblemList", (string)null);
                });

            modelBuilder.Entity("MediRecords.Domain.Entities.ProcedureCode", b =>
                {
                    b.Property<int>("CodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodeId"));

                    b.Property<string>("Code")
                        .HasColumnType("VARCHAR(20)");

                    b.Property<string>("Description")
                        .HasColumnType("VARCHAR(255)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(18,2)");

                    b.HasKey("CodeId");

                    b.ToTable("ProcedureCode");
                });

            modelBuilder.Entity("MediRecords.Domain.Entities.ProviderSchedule", b =>
                {
                    b.Property<int>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScheduleId"));

                    b.Property<string>("DayOfWeek")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProviderId")
                        .HasColumnType("int");

                    b.Property<int>("SlotDuration")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("ScheduleId");

                    b.HasIndex("ProviderId");

                    b.ToTable("ProviderSchedule");
                });

            modelBuilder.Entity("MediRecords.Domain.Entities.SOAPNote", b =>
                {
                    b.Property<int>("NoteId")
                        .HasColumnType("int");

                    b.Property<string>("Assessment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EncounterId")
                        .HasColumnType("int");

                    b.Property<string>("Objective")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Plan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("Subjective")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NoteId");

                    b.HasIndex("EncounterId");

                    b.ToTable("SOAPNote");
                });

            modelBuilder.Entity("MediRecords.Domain.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR(30)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("VARCHAR(15)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("UserId");

                    b.HasIndex("RoleId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("MediRecords.Domain.Entities.UserRole", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR(30)");

                    b.HasKey("RoleId");

                    b.ToTable("UserRole");
                });

            modelBuilder.Entity("MediRecords.Domain.Entities.VisitChargeRef", b =>
                {
                    b.Property<int>("ChargeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChargeId"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(18,2)");

                    b.Property<int>("CodeId")
                        .HasColumnType("int");

                    b.Property<int>("EncounterId")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("ChargeId");

                    b.HasIndex("CodeId");

                    b.HasIndex("EncounterId");

                    b.ToTable("VisitChargeRef");
                });

            modelBuilder.Entity("MediRecords.Models.NursingNote", b =>
                {
                    b.Property<int>("NursingNoteId")
                        .HasColumnType("int");

                    b.Property<int>("EncounterId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("RecordedBy")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)");

                    b.Property<DateTime>("RecordedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("NursingNoteId");

                    b.HasIndex("EncounterId");

                    b.ToTable("NursingNote");
                });

            modelBuilder.Entity("MediRecords.Models.VitalSign", b =>
                {
                    b.Property<int>("VitalId")
                        .HasColumnType("int");

                    b.Property<int>("EncounterId")
                        .HasColumnType("int");

                    b.Property<string>("RecordedBy")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)");

                    b.Property<DateTime>("RecordedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("VARCHAR(20)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)");

                    b.HasKey("VitalId");

                    b.HasIndex("EncounterId");

                    b.ToTable("VitalSign");
                });

            modelBuilder.Entity("MediRecords.Domain.Entities.Allergy", b =>
                {
                    b.HasOne("MediRecords.Domain.Entities.Patient", "PatientIdNavigation")
                        .WithMany("Allergies")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PatientIdNavigation");
                });

            modelBuilder.Entity("MediRecords.Domain.Entities.Appointment", b =>
                {
                    b.HasOne("MediRecords.Domain.Entities.Patient", "PatientIdNavigation")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MediRecords.Domain.Entities.User", "ProviderIdNavigation")
                        .WithMany("Appointments")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PatientIdNavigation");

                    b.Navigation("ProviderIdNavigation");
                });

            modelBuilder.Entity("MediRecords.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("MediRecords.Domain.Entities.User", "UserIdNavigation")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UserIdNavigation");
                });

            modelBuilder.Entity("MediRecords.Domain.Entities.CarePlan", b =>
                {
                    b.HasOne("MediRecords.Domain.Entities.Patient", "PatientIdNavigation")
                        .WithMany("CarePlans")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PatientIdNavigation");
                });

            modelBuilder.Entity("MediRecords.Domain.Entities.ClinicalTemplate", b =>
                {
                    b.HasOne("MediRecords.Domain.Entities.User", "CreatedByNavigation")
                        .WithMany("ClinicalTemplates")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByNavigation");
                });

            modelBuilder.Entity("MediRecords.Domain.Entities.Document", b =>
                {
                    b.HasOne("MediRecords.Domain.Entities.Encounter", "EncounterIdNavigation")
                        .WithMany("Documents")
                        .HasForeignKey("EncounterID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MediRecords.Domain.Entities.Patient", "PatientIdNavigation")
                        .WithMany("Documents")
                        .HasForeignKey("PatientID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EncounterIdNavigation");

                    b.Navigation("PatientIdNavigation");
                });

            modelBuilder.Entity("MediRecords.Domain.Entities.Encounter", b =>
                {
                    b.HasOne("MediRecords.Domain.Entities.Patient", "PatientIdNavigation")
                        .WithMany("Encounters")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MediRecords.Domain.Entities.User", "ProviderIdNavigation")
                        .WithMany("Encounters")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PatientIdNavigation");

                    b.Navigation("ProviderIdNavigation");
                });

            modelBuilder.Entity("MediRecords.Domain.Entities.FollowUp", b =>
                {
                    b.HasOne("MediRecords.Domain.Entities.Encounter", "EncounterIdNavigation")
                        .WithMany("FollowUps")
                        .HasForeignKey("EncounterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EncounterIdNavigation");
                });

            modelBuilder.Entity("MediRecords.Domain.Entities.ImagingOrder", b =>
                {
                    b.HasOne("MediRecords.Domain.Entities.Encounter", "EncounterIdNavigation")
                        .WithMany("ImagingOrders")
                        .HasForeignKey("EncounterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EncounterIdNavigation");
                });

            modelBuilder.Entity("MediRecords.Domain.Entities.ImagingReport", b =>
                {
                    b.HasOne("MediRecords.Domain.Entities.ImagingOrder", "ImagingOrderIdNavigation")
                        .WithMany("ImagingReports")
                        .HasForeignKey("ImagingOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImagingOrderIdNavigation");
                });

            modelBuilder.Entity("MediRecords.Domain.Entities.Immunization", b =>
                {
                    b.HasOne("MediRecords.Domain.Entities.Patient", "PatientIdNavigation")
                        .WithMany("Immunizations")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PatientIdNavigation");
                });

            modelBuilder.Entity("MediRecords.Domain.Entities.LabOrder", b =>
                {
                    b.HasOne("MediRecords.Domain.Entities.Encounter", "EncounterIdNavigation")
                        .WithMany("LabOrders")
                        .HasForeignKey("EncounterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MediRecords.Domain.Entities.User", "UserIdNavigation")
                        .WithMany("LabOrders")
                        .HasForeignKey("OrderedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EncounterIdNavigation");

                    b.Navigation("UserIdNavigation");
                });

            modelBuilder.Entity("MediRecords.Domain.Entities.LabResult", b =>
                {
                    b.HasOne("MediRecords.Domain.Entities.LabOrder", "LabOrderIdNavigation")
                        .WithMany("LabResults")
                        .HasForeignKey("LabOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LabOrderIdNavigation");
                });

            modelBuilder.Entity("MediRecords.Domain.Entities.MedicalHistory", b =>
                {
                    b.HasOne("MediRecords.Domain.Entities.Patient", "PatientIdNavigation")
                        .WithMany("MedicalHistories")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PatientIdNavigation");
                });

            modelBuilder.Entity("MediRecords.Domain.Entities.MedicationList", b =>
                {
                    b.HasOne("MediRecords.Domain.Entities.Patient", "PatientIdNavigation")
                        .WithMany("MedicationLists")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PatientIdNavigation");
                });

            modelBuilder.Entity("MediRecords.Domain.Entities.Notification", b =>
                {
                    b.HasOne("MediRecords.Domain.Entities.User", "UserIdNavigation")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserIdNavigation");
                });

            modelBuilder.Entity("MediRecords.Domain.Entities.Patient", b =>
                {
                    b.HasOne("MediRecords.Domain.Entities.User", "PrimaryProviderIdNavigation")
                        .WithMany("Patients")
                        .HasForeignKey("PrimaryProviderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("PrimaryProviderIdNavigation");
                });

            modelBuilder.Entity("MediRecords.Domain.Entities.Prescription", b =>
                {
                    b.HasOne("MediRecords.Domain.Entities.Encounter", "EncounterIdNavigation")
                        .WithMany("Prescriptions")
                        .HasForeignKey("EncounterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EncounterIdNavigation");
                });

            modelBuilder.Entity("MediRecords.Domain.Entities.PrescriptionItem", b =>
                {
                    b.HasOne("MediRecords.Domain.Entities.Prescription", "PrescriptionIdNavigation")
                        .WithMany("PrescriptionItems")
                        .HasForeignKey("PrescriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PrescriptionIdNavigation");
                });

            modelBuilder.Entity("MediRecords.Domain.Entities.ProblemList", b =>
                {
                    b.HasOne("MediRecords.Domain.Entities.Patient", "PatientIdNavigation")
                        .WithMany("ProblemLists")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PatientIdNavigation");
                });

            modelBuilder.Entity("MediRecords.Domain.Entities.ProviderSchedule", b =>
                {
                    b.HasOne("MediRecords.Domain.Entities.User", "ProviderIdNavigation")
                        .WithMany("ProviderSchedules")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProviderIdNavigation");
                });

            modelBuilder.Entity("MediRecords.Domain.Entities.SOAPNote", b =>
                {
                    b.HasOne("MediRecords.Domain.Entities.Encounter", "EncounterIdNavigation")
                        .WithMany("SOAPNotes")
                        .HasForeignKey("EncounterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EncounterIdNavigation");
                });

            modelBuilder.Entity("MediRecords.Domain.Entities.User", b =>
                {
                    b.HasOne("MediRecords.Domain.Entities.UserRole", "RoleIdNavigation")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RoleIdNavigation");
                });

            modelBuilder.Entity("MediRecords.Domain.Entities.VisitChargeRef", b =>
                {
                    b.HasOne("MediRecords.Domain.Entities.ProcedureCode", "ProcedureCodeNavigation")
                        .WithMany("VisitChargeRefs")
                        .HasForeignKey("CodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MediRecords.Domain.Entities.Encounter", "EncounterIdNavigation")
                        .WithMany("VisitChargeRefs")
                        .HasForeignKey("EncounterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EncounterIdNavigation");

                    b.Navigation("ProcedureCodeNavigation");
                });

            modelBuilder.Entity("MediRecords.Models.NursingNote", b =>
                {
                    b.HasOne("MediRecords.Domain.Entities.Encounter", "EncounterNavigation")
                        .WithMany("NursingNotes")
                        .HasForeignKey("EncounterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EncounterNavigation");
                });

            modelBuilder.Entity("MediRecords.Models.VitalSign", b =>
                {
                    b.HasOne("MediRecords.Domain.Entities.Encounter", "EncounterIdNavigation")
                        .WithMany("VitalSigns")
                        .HasForeignKey("EncounterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EncounterIdNavigation");
                });

            modelBuilder.Entity("MediRecords.Domain.Entities.Encounter", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("FollowUps");

                    b.Navigation("ImagingOrders");

                    b.Navigation("LabOrders");

                    b.Navigation("NursingNotes");

                    b.Navigation("Prescriptions");

                    b.Navigation("SOAPNotes");

                    b.Navigation("VisitChargeRefs");

                    b.Navigation("VitalSigns");
                });

            modelBuilder.Entity("MediRecords.Domain.Entities.ImagingOrder", b =>
                {
                    b.Navigation("ImagingReports");
                });

            modelBuilder.Entity("MediRecords.Domain.Entities.LabOrder", b =>
                {
                    b.Navigation("LabResults");
                });

            modelBuilder.Entity("MediRecords.Domain.Entities.Patient", b =>
                {
                    b.Navigation("Allergies");

                    b.Navigation("Appointments");

                    b.Navigation("CarePlans");

                    b.Navigation("Documents");

                    b.Navigation("Encounters");

                    b.Navigation("Immunizations");

                    b.Navigation("MedicalHistories");

                    b.Navigation("MedicationLists");

                    b.Navigation("ProblemLists");
                });

            modelBuilder.Entity("MediRecords.Domain.Entities.Prescription", b =>
                {
                    b.Navigation("PrescriptionItems");
                });

            modelBuilder.Entity("MediRecords.Domain.Entities.ProcedureCode", b =>
                {
                    b.Navigation("VisitChargeRefs");
                });

            modelBuilder.Entity("MediRecords.Domain.Entities.User", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("AuditLogs");

                    b.Navigation("ClinicalTemplates");

                    b.Navigation("Encounters");

                    b.Navigation("LabOrders");

                    b.Navigation("Notifications");

                    b.Navigation("Patients");

                    b.Navigation("ProviderSchedules");
                });

            modelBuilder.Entity("MediRecords.Domain.Entities.UserRole", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
